package com.safeher.authservice.event;

import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class AuthUserRegisteredEvent {
    /** The UUID generated by Auth Service – becomes the authUserId in User Service */
    private UUID authUserId;
    private String username;
    private String email;
    private String role;
    private String displayName;
    private String city;
    private String country;
    @Builder.Default private OffsetDateTime occurredAt = OffsetDateTime.now();
}
